---
- name: Add SSH key to known hosts
  hosts: web
  tasks:
    - name: Add 192.168.56.10 to known_hosts
      ansible.builtin.known_hosts:
        name: "{{ ansible_env.HOME }}/.ssh/known_hosts"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa 192.168.56.10') }}"
        state: present
- name: Install and configure nginx
  hosts: web
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Ensure nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create custom index.html
      template:
        src: "index.html.j2"
        dest: "/usr/share/nginx/html/index.html"
